name: Update RSS Feed

on:
  schedule:
    - cron: '0 0 * * *'  # runs at midnight UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository using your PAT for write access
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      # Step 2: Set up Python (adjust the version as needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (make sure your requirements.txt is in the repo)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the scraper script
      - name: Run scraper
        run: python scraper.py

      # (Optional) Debug: List files in the repo root to verify rss.xml is created
      - name: List files in repo root
        run: ls -la

      # Step 5: Copy rss.xml to a txt file (rss.txt)
      - name: Copy RSS XML to TXT
        run: |
          if [ -f rss.xml ]; then
            cp rss.xml rss.txt
          else
            echo "rss.xml not found, cannot create rss.txt"
            exit 1
          fi

      # Step 6: Commit and push the updated files (rss.xml and rss.txt)
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -f rss.xml ]; then
            git add rss.xml rss.txt
            git commit -m "Update RSS feed [skip ci]" || echo "No changes to commit"
            git push origin HEAD:main
          else
            echo "rss.xml not found, skipping commit"
          fi
