name: Update RSS Feed

# This workflow runs daily (you can adjust the cron expression) and also supports manual runs.
on:
  schedule:
    - cron: '0 0 * * *'  # runs at midnight UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository using your PAT for write access
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      # Step 2: Set up Python (adjust the version as needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (make sure your requirements.txt is in the repo)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the scraper script
      - name: Run scraper
        run: python scraper.py

      # (Optional) Step: List files to verify rss.xml is created in the repo root
      - name: List files in repo root (debug)
        run: ls -la

      # Step 5: Commit and push the updated rss.xml (only if the file exists)
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -f rss.xml ]; then
            git add rss.xml
            git commit -m "Update RSS feed [skip ci]" || echo "No changes to commit"
            git push origin HEAD:main
          else
            echo "rss.xml not found, skipping commit"
          fi
